---
name: Test-File-Contents
version: 0.05
author:
  - 'Kirrily Robert <skud@cpan.org>'
abstract: Test routines for examining the contents of files
license: perl
requires:
  Test::More: 0
provides:
  Test::File::Contents:
    file: lib/Test/File/Contents.pm
    version: 0.05
generated_by: Module::Build version 0.26
