--- #YAML:1.0
name: Test-File-Contents
version: 0.03
author:
  - Kirrily Robert <skud@cpan.org>
abstract: Test routines for examining the contents of files
license: unknown
generated_by: Module::Build version 0.2611, without YAML.pm
